### ISSUE TITLE
Technical report export

### ISSUE THREAD

**Issue by jgeudens** [ModbusScope/ModbusScope#133]
A technical report can consist of:

- Export of current settings (mbs file)
- Export of log data
- Export of data (csv file)
- Screenshot of current graph

**Comment by FranVojvoda** [comment]
Hello! I am doing tests with ModbusScope and I think it would be interesting to add an option so that the CSV Log is divided into time slots, it would help the subsequent analysis of it (for example, half an hour, one hour).

Probably a timestamp in the name would help.

Thank you!
