### ISSUE TITLE
Show special marker for unknown values

### ISSUE THREAD

**Issue by ben-edna** [ModbusScope/ModbusScope#167]
Given modbusscope is reading from register 40001
When the communication fails 
Then currently a "normal filled" dot is shown with the value zero.

To make the distinction more clear this could be replaced by a cross 'X' or a unfilled dot. If the value could be zero it could otherwise lead to misinterpretations.

As a sidenote the export/import of csv files might need some adaptation since, these export a zero value as well. Maybe replace this with no value.

**Comment by jgeudens** [comment]
Interesting idea. I have heard this idea a few times before. 

A cross 'X' or unfilled dot is an option. But at what Y position should it be drawn?

QCustomplot supports NaN as a gap in the graph (https://www.qcustomplot.com/documentation/classQCPGraph.html#details). But what should happen when the values are invalid from the start? There won't be any graph points to show. This might be confusing.

Some use cases that also need to be taking into consideration.
- [ ] Most recent values are shown in legend
- [ ] Tool tip shows value
- [ ] Internal calculations on data
- [ ] Marker (average, min, max, ...)
