### ISSUE TITLE
Feature request: Create screenshot during run

### ISSUE THREAD

**Issue by spoorcc** [ModbusScope/ModbusScope#280]
When running a long-running test with a sliding window, it is sometimes useful to create an intermediate screenshot.
Currently it is only possible to stop the logging and create an image.

Would be nice to have a [camera icon ](https://lucide.dev/icons/camera)in the ribbon that can take a screenshot while running

**Comment by jgeudens** [comment]
Released in v3.8.1

**Comment by spoorcc** [comment]
Thanks from Italy! 🇮🇹
