### ISSUE TITLE
Mark invalid expression cells as red

### ISSUE THREAD

**Issue by ben-edna** [ModbusScope/ModbusScope#286]
As extension to #284  (and #285 ) if an expression is invalid this is not directly obvious:

![image](https://github.com/ModbusScope/ModbusScope/assets/37540691/fde25ecd-b7e9-46a8-9b02-ba1736d6da72)

However in the expression editor it is:

![image](https://github.com/ModbusScope/ModbusScope/assets/37540691/4b05333c-592b-4247-b148-ee272b8f22b0)

Bonus points for a note on hover with the error message in it ("Unexpected token ....")

**Comment by jgeudens** [comment]
Implemented with #303
